hakari-package = "workspace-hack"
resolver = "3"
dep-format-version = "4"

platforms = [
    "x86_64-unknown-linux-gnu",
    "aarch64-apple-darwin",
]

[traversal-excludes]
third-party = [
    { name = "eigensdk" },
]
