#![allow(unused_imports, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod r#upgradetangle;
pub mod r#iblueprintservicemanager;
pub mod r#itangle;
pub mod r#itangleadmin;
pub mod r#itanglefull;
pub mod r#itangleblueprints;
pub mod r#itanglegovernance;
pub mod r#itangletoken;
pub mod r#itanglejobs;
pub mod r#itangleoperators;
pub mod r#itanglerewards;
pub mod r#itangleservices;
pub mod r#itangleslashing;
pub mod r#tangle;
pub mod r#tangletest;
pub mod r#tanglegovernor;
pub mod r#tanglemetrics;
pub mod r#tanglestorage;
pub mod r#tangletimelock;
pub mod r#tangletoken;
